/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Question } from "@prisma/client";

export class QuestionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.QuestionCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.QuestionCountArgs>
  ): Promise<number> {
    return this.prisma.question.count(args);
  }

  async questions<T extends Prisma.QuestionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.QuestionFindManyArgs>
  ): Promise<Question[]> {
    return this.prisma.question.findMany(args);
  }
  async question<T extends Prisma.QuestionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.QuestionFindUniqueArgs>
  ): Promise<Question | null> {
    return this.prisma.question.findUnique(args);
  }
  async createQuestion<T extends Prisma.QuestionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.QuestionCreateArgs>
  ): Promise<Question> {
    return this.prisma.question.create<T>(args);
  }
  async updateQuestion<T extends Prisma.QuestionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.QuestionUpdateArgs>
  ): Promise<Question> {
    return this.prisma.question.update<T>(args);
  }
  async deleteQuestion<T extends Prisma.QuestionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.QuestionDeleteArgs>
  ): Promise<Question> {
    return this.prisma.question.delete(args);
  }
}
