/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Assessment, // @ts-ignore
  Risk, // @ts-ignore
  Application, // @ts-ignore
  User,
} from "@prisma/client";

export class AssessmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.AssessmentCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssessmentCountArgs>
  ): Promise<number> {
    return this.prisma.assessment.count(args);
  }

  async assessments<T extends Prisma.AssessmentFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssessmentFindManyArgs>
  ): Promise<Assessment[]> {
    return this.prisma.assessment.findMany(args);
  }
  async assessment<T extends Prisma.AssessmentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssessmentFindUniqueArgs>
  ): Promise<Assessment | null> {
    return this.prisma.assessment.findUnique(args);
  }
  async createAssessment<T extends Prisma.AssessmentCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssessmentCreateArgs>
  ): Promise<Assessment> {
    return this.prisma.assessment.create<T>(args);
  }
  async updateAssessment<T extends Prisma.AssessmentUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssessmentUpdateArgs>
  ): Promise<Assessment> {
    return this.prisma.assessment.update<T>(args);
  }
  async deleteAssessment<T extends Prisma.AssessmentDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssessmentDeleteArgs>
  ): Promise<Assessment> {
    return this.prisma.assessment.delete(args);
  }

  async findRisks(
    parentId: string,
    args: Prisma.RiskFindManyArgs
  ): Promise<Risk[]> {
    return this.prisma.assessment
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .risks(args);
  }

  async getApplication(parentId: string): Promise<Application | null> {
    return this.prisma.assessment
      .findUnique({
        where: { id: parentId },
      })
      .application();
  }

  async getAssessor(parentId: string): Promise<User | null> {
    return this.prisma.assessment
      .findUnique({
        where: { id: parentId },
      })
      .assessor();
  }
}
