/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssessmentWhereUniqueInput } from "../../assessment/base/AssessmentWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { QuestionsRIskListRelationFilter } from "../../questionsRIsk/base/QuestionsRIskListRelationFilter";

@InputType()
class RiskWhereInput {
  @ApiProperty({
    required: false,
    type: () => AssessmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AssessmentWhereUniqueInput)
  @IsOptional()
  @Field(() => AssessmentWhereUniqueInput, {
    nullable: true,
  })
  assessment?: AssessmentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  mitigationPlan?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  owner?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => QuestionsRIskListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QuestionsRIskListRelationFilter)
  @IsOptional()
  @Field(() => QuestionsRIskListRelationFilter, {
    nullable: true,
  })
  questions?: QuestionsRIskListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  summary?: StringNullableFilter;
}

export { RiskWhereInput as RiskWhereInput };
