/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RiskService } from "../risk.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RiskCreateInput } from "./RiskCreateInput";
import { Risk } from "./Risk";
import { RiskFindManyArgs } from "./RiskFindManyArgs";
import { RiskWhereUniqueInput } from "./RiskWhereUniqueInput";
import { RiskUpdateInput } from "./RiskUpdateInput";
import { QuestionsRIskFindManyArgs } from "../../questionsRIsk/base/QuestionsRIskFindManyArgs";
import { QuestionsRIsk } from "../../questionsRIsk/base/QuestionsRIsk";
import { QuestionsRIskWhereUniqueInput } from "../../questionsRIsk/base/QuestionsRIskWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RiskControllerBase {
  constructor(
    protected readonly service: RiskService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Risk })
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRisk(@common.Body() data: RiskCreateInput): Promise<Risk> {
    return await this.service.createRisk({
      data: data,
      select: {
        createdAt: true,
        id: true,
        mitigationPlan: true,
        owner: true,
        summary: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Risk] })
  @ApiNestedQuery(RiskFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async risks(@common.Req() request: Request): Promise<Risk[]> {
    const args = plainToClass(RiskFindManyArgs, request.query);
    return this.service.risks({
      ...args,
      select: {
        createdAt: true,
        id: true,
        mitigationPlan: true,
        owner: true,
        summary: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Risk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async risk(
    @common.Param() params: RiskWhereUniqueInput
  ): Promise<Risk | null> {
    const result = await this.service.risk({
      where: params,
      select: {
        createdAt: true,
        id: true,
        mitigationPlan: true,
        owner: true,
        summary: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Risk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRisk(
    @common.Param() params: RiskWhereUniqueInput,
    @common.Body() data: RiskUpdateInput
  ): Promise<Risk | null> {
    try {
      return await this.service.updateRisk({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          mitigationPlan: true,
          owner: true,
          summary: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Risk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRisk(
    @common.Param() params: RiskWhereUniqueInput
  ): Promise<Risk | null> {
    try {
      return await this.service.deleteRisk({
        where: params,
        select: {
          createdAt: true,
          id: true,
          mitigationPlan: true,
          owner: true,
          summary: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/questions")
  @ApiNestedQuery(QuestionsRIskFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "QuestionsRIsk",
    action: "read",
    possession: "any",
  })
  async findQuestions(
    @common.Req() request: Request,
    @common.Param() params: RiskWhereUniqueInput
  ): Promise<QuestionsRIsk[]> {
    const query = plainToClass(QuestionsRIskFindManyArgs, request.query);
    const results = await this.service.findQuestions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        question: {
          select: {
            id: true,
          },
        },

        risk: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/questions")
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "update",
    possession: "any",
  })
  async connectQuestions(
    @common.Param() params: RiskWhereUniqueInput,
    @common.Body() body: QuestionsRIskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        connect: body,
      },
    };
    await this.service.updateRisk({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/questions")
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "update",
    possession: "any",
  })
  async updateQuestions(
    @common.Param() params: RiskWhereUniqueInput,
    @common.Body() body: QuestionsRIskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        set: body,
      },
    };
    await this.service.updateRisk({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/questions")
  @nestAccessControl.UseRoles({
    resource: "Risk",
    action: "update",
    possession: "any",
  })
  async disconnectQuestions(
    @common.Param() params: RiskWhereUniqueInput,
    @common.Body() body: QuestionsRIskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        disconnect: body,
      },
    };
    await this.service.updateRisk({
      where: params,
      data,
      select: { id: true },
    });
  }
}
