/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { QuestionsRIskService } from "../questionsRIsk.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { QuestionsRIskCreateInput } from "./QuestionsRIskCreateInput";
import { QuestionsRIsk } from "./QuestionsRIsk";
import { QuestionsRIskFindManyArgs } from "./QuestionsRIskFindManyArgs";
import { QuestionsRIskWhereUniqueInput } from "./QuestionsRIskWhereUniqueInput";
import { QuestionsRIskUpdateInput } from "./QuestionsRIskUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class QuestionsRIskControllerBase {
  constructor(
    protected readonly service: QuestionsRIskService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: QuestionsRIsk })
  @nestAccessControl.UseRoles({
    resource: "QuestionsRIsk",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createQuestionsRIsk(
    @common.Body() data: QuestionsRIskCreateInput
  ): Promise<QuestionsRIsk> {
    return await this.service.createQuestionsRIsk({
      data: {
        ...data,

        question: data.question
          ? {
              connect: data.question,
            }
          : undefined,

        risk: data.risk
          ? {
              connect: data.risk,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        question: {
          select: {
            id: true,
          },
        },

        risk: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [QuestionsRIsk] })
  @ApiNestedQuery(QuestionsRIskFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "QuestionsRIsk",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async questionsRIsks(
    @common.Req() request: Request
  ): Promise<QuestionsRIsk[]> {
    const args = plainToClass(QuestionsRIskFindManyArgs, request.query);
    return this.service.questionsRIsks({
      ...args,
      select: {
        createdAt: true,
        id: true,

        question: {
          select: {
            id: true,
          },
        },

        risk: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: QuestionsRIsk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "QuestionsRIsk",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async questionsRIsk(
    @common.Param() params: QuestionsRIskWhereUniqueInput
  ): Promise<QuestionsRIsk | null> {
    const result = await this.service.questionsRIsk({
      where: params,
      select: {
        createdAt: true,
        id: true,

        question: {
          select: {
            id: true,
          },
        },

        risk: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: QuestionsRIsk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "QuestionsRIsk",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateQuestionsRIsk(
    @common.Param() params: QuestionsRIskWhereUniqueInput,
    @common.Body() data: QuestionsRIskUpdateInput
  ): Promise<QuestionsRIsk | null> {
    try {
      return await this.service.updateQuestionsRIsk({
        where: params,
        data: {
          ...data,

          question: data.question
            ? {
                connect: data.question,
              }
            : undefined,

          risk: data.risk
            ? {
                connect: data.risk,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          question: {
            select: {
              id: true,
            },
          },

          risk: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: QuestionsRIsk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "QuestionsRIsk",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteQuestionsRIsk(
    @common.Param() params: QuestionsRIskWhereUniqueInput
  ): Promise<QuestionsRIsk | null> {
    try {
      return await this.service.deleteQuestionsRIsk({
        where: params,
        select: {
          createdAt: true,
          id: true,

          question: {
            select: {
              id: true,
            },
          },

          risk: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
